// Generate supabase/migrations/0028_company_universe_seed.sql from
// data/company-universe.csv + data/company-universe-boards.json.
//
//   node scripts/probe-company-boards.ts   # 1. verify boards (network)
//   node scripts/build-company-universe.ts # 2. regenerate the seed SQL
//
// To refresh the list later: re-export the "All Companies (Unique)" sheet to
// data/company-universe.csv, re-run both scripts, and ship the regenerated
// seed as a NEW migration (copy the output to the next migration number) —
// every statement is an upsert, so replaying it over existing rows is safe and
// never clobbers resolver progress on rows it doesn't have a board for.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { buildUniverse, parseUniverseCsv, type UniverseEntry } from "../src/lib/jobs/universe/classify.ts";

const CSV_PATH = new URL("../data/company-universe.csv", import.meta.url);
const BOARDS_PATH = new URL("../data/company-universe-boards.json", import.meta.url);
const OUT_ARG = process.argv.find((a) => a.startsWith("--out="));
const OUT_PATH = OUT_ARG
  ? new URL(`../${OUT_ARG.slice(6)}`, import.meta.url)
  : new URL("../supabase/migrations/0028_company_universe_seed.sql", import.meta.url);

interface ProbeResult {
  name: string;
  ats: string | null;
  slug: string | null;
  jobs: number;
  checked_at: string;
}

const lit = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const n = (v: number | null | undefined) => (v == null ? "null" : String(v));
const b = (v: boolean) => (v ? "true" : "false");
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(lit).join(",")}]::text[]` : `'{}'::text[]`);

function universeValues(e: UniverseEntry, probe: ProbeResult | undefined): string {
  return `(${[
    lit(e.name),
    lit(e.match_key),
    arr(e.aliases),
    b(e.in_fortune500),
    b(e.in_top_startups),
    b(e.in_top_h1b),
    n(e.fortune_rank),
    n(e.revenue_musd),
    n(e.startup_rank),
    n(e.valuation_busd),
    lit(e.investors),
    n(e.h1b_rank),
    n(e.h1b_approvals),
    arr(e.h1b_entities),
    lit(e.industry),
    lit(e.hq),
    lit(e.org_type),
    arr(e.sectors),
    lit(e.size_bucket),
    probe ? `${lit(probe.checked_at)}::timestamptz` : "null",
  ].join(", ")})`;
}

function main() {
  const universe = buildUniverse(parseUniverseCsv(readFileSync(CSV_PATH, "utf8")));
  const probes: Record<string, ProbeResult> = existsSync(BOARDS_PATH)
    ? (JSON.parse(readFileSync(BOARDS_PATH, "utf8")).results as Record<string, ProbeResult>)
    : {};

  const boards = universe
    .map((e) => ({ e, p: probes[e.match_key] }))
    .filter((x): x is { e: UniverseEntry; p: ProbeResult } => !!x.p?.ats && !!x.p.slug);
  const probed = universe.filter((e) => probes[e.match_key]).length;

  const sql = `-- GENERATED by scripts/build-company-universe.ts — do not edit by hand.
-- ${universe.length} universe employers; ${probed} slug-probed; ${boards.length} with a verified
-- Greenhouse/Lever/Ashby board. Idempotent: every statement is an upsert.

-- 1. universe rows (list data refreshes; resolver state is left alone).
insert into company_universe (
  name, match_key, aliases, in_fortune500, in_top_startups, in_top_h1b,
  fortune_rank, revenue_musd, startup_rank, valuation_busd, investors,
  h1b_rank, h1b_approvals, h1b_entities, industry, hq, org_type, sectors,
  size_bucket, probed_at
) values
${universe.map((e) => universeValues(e, probes[e.match_key])).join(",\n")}
on conflict (match_key) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  in_fortune500 = excluded.in_fortune500,
  in_top_startups = excluded.in_top_startups,
  in_top_h1b = excluded.in_top_h1b,
  fortune_rank = excluded.fortune_rank,
  revenue_musd = excluded.revenue_musd,
  startup_rank = excluded.startup_rank,
  valuation_busd = excluded.valuation_busd,
  investors = excluded.investors,
  h1b_rank = excluded.h1b_rank,
  h1b_approvals = excluded.h1b_approvals,
  h1b_entities = excluded.h1b_entities,
  industry = excluded.industry,
  hq = excluded.hq,
  org_type = excluded.org_type,
  -- keep LLM-refined sectors once the refinement pass has run
  sectors = case when company_universe.sectors_refined_at is null then excluded.sectors else company_universe.sectors end,
  size_bucket = excluded.size_bucket,
  probed_at = coalesce(company_universe.probed_at, excluded.probed_at),
  updated_at = now();

-- 2. verified boards → scannable catalog rows. An existing row on the same
--    board (a seed or LLM-resolved company) is linked, keeping its curated
--    sectors (unioned) and size.
insert into companies (name, normalized, ats, slug, sectors, size_bucket, source, verified_at, universe_id, org_type)
select u.name, lower(u.name), v.ats, v.slug, u.sectors, u.size_bucket, 'universe', now(), u.id, u.org_type
from (values
${boards.map(({ e, p }) => `  (${lit(e.match_key)}, ${lit(p.ats)}, ${lit(p.slug)})`).join(",\n")}
) as v(match_key, ats, slug)
join company_universe u on u.match_key = v.match_key
on conflict (ats, slug) do update set
  universe_id = excluded.universe_id,
  org_type = excluded.org_type,
  sectors = array(select distinct unnest(companies.sectors || excluded.sectors)),
  size_bucket = coalesce(companies.size_bucket, excluded.size_bucket);

-- 3. link catalog companies that already track a universe employer under the
--    same display name (e.g. seeded on a board the probe didn't try).
update companies c
set universe_id = u.id, org_type = u.org_type
from company_universe u
where c.universe_id is null and c.normalized = lower(u.name);

-- 4. resolver state: linked rows are resolved; slug-probed rows without a
--    board stay pending (the server resolver moves on to Workday / LLM
--    discovery for them — see src/lib/jobs/universe/resolve.ts).
update company_universe u
set resolve_status = 'resolved',
    resolved_at = coalesce(u.resolved_at, now()),
    resolve_note = 'board verified',
    updated_at = now()
where u.resolve_status <> 'resolved'
  and exists (select 1 from companies c where c.universe_id = u.id);
`;
  writeFileSync(OUT_PATH, sql);
  console.log(`wrote ${OUT_PATH.pathname}: ${universe.length} universe rows, ${boards.length} boards`);
}

main();
